-- 적재 검증용 조회 쿼리

-- 전체 건수 (317건이어야 함)
SELECT COUNT(*) AS TOTAL FROM TBL_DEMENTIA_CENTER;

-- 센터 유형별 건수 (치매안심센터 307 / 광역치매센터 9 / 치매상담전화센터 1)
SELECT CNTER_SE, COUNT(*) AS CNT
FROM TBL_DEMENTIA_CENTER
GROUP BY CNTER_SE
ORDER BY CNT DESC;

-- 좌표 보유율 (전부 보유해야 함)
SELECT COUNT(*) AS HAS_COORD
FROM TBL_DEMENTIA_CENTER
WHERE LATITUDE IS NOT NULL AND LONGITUDE IS NOT NULL;

-- 지자체별 상위 10개 (Oracle 11g은 FETCH FIRST 미지원이라 ROWNUM 사용)
SELECT * FROM (
    SELECT INSTT_NM, COUNT(*) AS CNT
    FROM TBL_DEMENTIA_CENTER
    GROUP BY INSTT_NM
    ORDER BY CNT DESC
) WHERE ROWNUM <= 10;
